package payment

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"time"

	"go.uber.org/zap"
)

type MercadoPagoClient struct {
	httpClient *http.Client
	logger     *zap.Logger
}

func NewMercadoPagoClient(logger *zap.Logger) *MercadoPagoClient {
	return &MercadoPagoClient{
		httpClient: &http.Client{Timeout: 30 * time.Second},
		logger:     logger,
	}
}

// ==========================================
// PIX (QR Code & CopiaCola)
// ==========================================

type PixPaymentRequest struct {
	TransactionAmount float64 `json:"transaction_amount"`
	Description       string  `json:"description"`
	PaymentMethodID   string  `json:"payment_method_id"` // "pix"
	Payer             struct {
		Email          string `json:"email"`
		FirstName      string `json:"first_name"`
		LastName       string `json:"last_name"`
		Identification struct {
			Type   string `json:"type"`
			Number string `json:"number"`
		} `json:"identification"`
	} `json:"payer"`
}

type PixPaymentResponse struct {
	ID                 int64  `json:"id"`
	Status             string `json:"status"` // "pending", "approved", etc
	StatusDetail       string `json:"status_detail"`
	PointOfInteraction struct {
		TransactionData struct {
			QRCode       string `json:"qr_code"`
			QRCodeBase64 string `json:"qr_code_base64"`
		} `json:"transaction_data"`
	} `json:"point_of_interaction"`
}

func (client *MercadoPagoClient) CreatePixPayment(ctx context.Context, accessToken string, idempotencyKey string, req PixPaymentRequest) (*PixPaymentResponse, error) {
	url := "https://api.mercadopago.com/v1/payments"

	req.PaymentMethodID = "pix"

	bodyBytes, _ := json.Marshal(req)
	httpReq, _ := http.NewRequestWithContext(ctx, "POST", url, bytes.NewBuffer(bodyBytes))

	httpReq.Header.Set("Authorization", "Bearer "+accessToken)
	httpReq.Header.Set("Content-Type", "application/json")
	httpReq.Header.Set("X-Idempotency-Key", idempotencyKey)

	resp, err := client.httpClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("mp api error: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		errorBody, _ := io.ReadAll(resp.Body)
		client.logger.Error("MercadoPago PIX creation failed",
			zap.Int("status", resp.StatusCode),
			zap.String("response", string(errorBody)),
		)
		return nil, fmt.Errorf("mercadopago returned status %d", resp.StatusCode)
	}

	var pixResp PixPaymentResponse
	if err := json.NewDecoder(resp.Body).Decode(&pixResp); err != nil {
		return nil, fmt.Errorf("failed to decode mp pix response: %w", err)
	}

	return &pixResp, nil
}

type PaymentStatusResponse struct {
	ID           int64  `json:"id"`
	Status       string `json:"status"`
	StatusDetail string `json:"status_detail"`
}

func (client *MercadoPagoClient) GetPayment(ctx context.Context, accessToken string, paymentID string) (*PaymentStatusResponse, error) {
	url := fmt.Sprintf("https://api.mercadopago.com/v1/payments/%s", paymentID)

	httpReq, _ := http.NewRequestWithContext(ctx, "GET", url, nil)
	httpReq.Header.Set("Authorization", "Bearer "+accessToken)

	resp, err := client.httpClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("mp api error: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		errorBody, _ := io.ReadAll(resp.Body)
		client.logger.Error("MercadoPago payment lookup failed",
			zap.Int("status", resp.StatusCode),
			zap.String("response", string(errorBody)),
			zap.String("payment_id", paymentID),
		)
		return nil, fmt.Errorf("mercadopago returned status %d", resp.StatusCode)
	}

	var paymentResp PaymentStatusResponse
	if err := json.NewDecoder(resp.Body).Decode(&paymentResp); err != nil {
		return nil, fmt.Errorf("failed to decode mp payment response: %w", err)
	}

	return &paymentResp, nil
}

// ==========================================
// Cartão de Crédito / Débito (Tokenizado)
// ==========================================

type CardPaymentRequest struct {
	TransactionAmount float64 `json:"transaction_amount"`
	Token             string  `json:"token"` // PCI Compliant Token generated by MP Frontend SDK
	Description       string  `json:"description"`
	Installments      int     `json:"installments"`
	PaymentMethodID   string  `json:"payment_method_id"` // "visa", "master", "debvisa"...
	IssuerID          string  `json:"issuer_id"`
	Payer             struct {
		Email          string `json:"email"`
		Identification struct {
			Type   string `json:"type"`
			Number string `json:"number"`
		} `json:"identification"`
	} `json:"payer"`
}

type CardPaymentResponse struct {
	ID           int64  `json:"id"`
	Status       string `json:"status"` // "approved", "rejected", "in_process"
	StatusDetail string `json:"status_detail"`
}

func (client *MercadoPagoClient) CreateCardPayment(ctx context.Context, accessToken string, idempotencyKey string, req CardPaymentRequest) (*CardPaymentResponse, error) {
	url := "https://api.mercadopago.com/v1/payments"

	bodyBytes, _ := json.Marshal(req)
	httpReq, _ := http.NewRequestWithContext(ctx, "POST", url, bytes.NewBuffer(bodyBytes))

	httpReq.Header.Set("Authorization", "Bearer "+accessToken)
	httpReq.Header.Set("Content-Type", "application/json")
	httpReq.Header.Set("X-Idempotency-Key", idempotencyKey)

	resp, err := client.httpClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("mp api error: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		errorBody, _ := io.ReadAll(resp.Body)
		client.logger.Error("MercadoPago Card payment failed",
			zap.Int("status", resp.StatusCode),
			zap.String("response", string(errorBody)),
		)
		return nil, fmt.Errorf("mercadopago returned status %d", resp.StatusCode)
	}

	var cardResp CardPaymentResponse
	if err := json.NewDecoder(resp.Body).Decode(&cardResp); err != nil {
		return nil, fmt.Errorf("failed to decode mp card response: %w", err)
	}

	return &cardResp, nil
}
