ALTER TABLE tenants
    ADD COLUMN IF NOT EXISTS waba_id VARCHAR(255),
    ADD COLUMN IF NOT EXISTS meta_token TEXT,
    ADD COLUMN IF NOT EXISTS wallet_balance NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    ADD COLUMN IF NOT EXISTS billing_plan VARCHAR(20) NOT NULL DEFAULT 'pre_paid',
    ADD COLUMN IF NOT EXISTS is_open BOOLEAN NOT NULL DEFAULT FALSE;

CREATE INDEX IF NOT EXISTS idx_tenants_waba_id ON tenants(waba_id);
